server:
  port: 9099
  
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/fintech
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
fintech.security.jwt:
  tokenExpirationTime: 50 # Number of minutes
  tokenIssuer: http://localhost:8080
  tokenSigningKey: cbd37ca94f2a917b490cc4c49bb602911cbe702650dab4c3131b7b0b61d03ac1
